### PR TITLE
Update Storybook addon metadata

### PR DESCRIPTION
**Pull request by coderkevin**
Hey react-theming! We've created a catalog of Storybook addons and yours is included: https://storybook.js.org/addons/@react-theming/storybook-addon

To make your addon more discoverable in the catalog, we've curated some of its metadata, and I've included those edits in this PR.

To learn more about the catalog metadata, check out our documentation: https://storybook.js.org/docs/react/addons/addon-catalog

### CODE REVIEW

**Comment by UsulPro** [comment]
Hey @coderkevin thanks.... looks it's an auto created PR as it tries to change existing metadata 😄

**Comment by coderkevin** [comment]
Hi @UsulPro, yeah I'm running a script to help me get these PRs out and they're based on human-curated data we've added for the catalog. If you've made any recent changes to your metadata since we added some of our own, it may be incompatible. It looks like all you really. need here are the extra 2 keywords. Would you like me to modify this PR to reflect that?

**Comment by UsulPro** [comment]
Thanks @coderkevin 
do I need to publish updates to NPM to them take affect?

**Comment by coderkevin** [comment]
Thanks! Yes, the changes will be reflected after the next NPM release.

**Pull request merged**
